"""Convert the trained robustness CORRECTION to RobustnessNet.mlpackage.

The exported graph emits C in [0,1] -- the confidence the analytic mask is
multiplied by, NOT the mask. The sigmoid is inside the graph on purpose: the
guarantee that the network can never raise R has to survive export, and a
graph that emitted a logit would put that guarantee in the hands of whatever
C++ applies it.

Input normalisation is folded in as a fixed scale/bias layer, so the C++ side
hands over raw feature planes and needs no constant table that could drift out
of step with the weights.

The model is fully convolutional, so it is exported with flexible spatial
dimensions: the guide resolution follows the sensor, and the same weights
serve any of them.

Verify before bundling. The Core ML wrapper fails CLOSED on a channel-count
mismatch -- it logs and returns false and the pipeline uses the plain analytic
mask -- so an .mlmodelc built for the wrong IN_CH looks exactly like "the
correction changed nothing". This script prints the spec's input shape at the
end; check it against kRobustnessNnChannels before copying anything into
Resources/, and check that the bundled file is newer than the .pt it came
from.
"""
import json, os, sys
import numpy as np
import torch
import torch.nn as nn

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from train_rob import RobNet, IN_CH

HERE = os.path.dirname(os.path.abspath(__file__))
CKPT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "robnet.pt")
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, "RobustnessNet.mlpackage")


class Wrapped(nn.Module):
    """Normalisation + network, so the exported graph is self-contained."""
    def __init__(self, core, mu, sd):
        super().__init__()
        self.core = core
        self.register_buffer("mu", torch.tensor(mu, dtype=torch.float32).view(1, -1, 1, 1))
        self.register_buffer("sd", torch.tensor(sd, dtype=torch.float32).view(1, -1, 1, 1))

    def forward(self, x):
        return self.core((x - self.mu) / self.sd)


def main():
    import coremltools as ct

    ck = torch.load(CKPT, weights_only=False, map_location="cpu")
    if ck.get("in_ch", IN_CH) != IN_CH:
        raise SystemExit(f"checkpoint was trained with {ck['in_ch']} input "
                         f"channels, train_rob.py now says {IN_CH}")
    if ck.get("drop_ch"):
        # Those channels were zeroed during training, so the weights on them
        # are whatever the initialiser left. Exporting without reproducing the
        # zeroing gives a model that behaves differently from the one measured.
        print(f"NOTE: checkpoint drops input channels {ck['drop_ch']}; "
              "folding the zeroing into the exported first layer")
    core = RobNet()
    core.load_state_dict(ck["state"])
    for c in ck.get("drop_ch", []):
        with torch.no_grad():
            core.net[0].weight[:, c] = 0.0
    model = Wrapped(core, ck["mu"], ck["sd"]).eval()

    example = torch.zeros(1, IN_CH, 64, 64)
    with torch.no_grad():
        traced = torch.jit.trace(model, example)

    # Guide resolution is sensor-dependent; keep H/W symbolic rather than
    # baking in one device's dimensions.
    h = ct.RangeDim(lower_bound=64, upper_bound=4096, default=1512)
    w = ct.RangeDim(lower_bound=64, upper_bound=4096, default=2016)

    # mlprogram is the better target (fp16 weights, newer runtime) but its
    # weight blob is written by a native extension that coremltools ships
    # only for macOS/Linux. Fall back to the neuralnetwork format, which
    # serialises weights into the protobuf itself and therefore converts
    # anywhere -- same graph, same numerics, slightly older runtime.
    try:
        mlmodel = ct.convert(
            traced,
            inputs=[ct.TensorType(name="features", shape=(1, IN_CH, h, w),
                                  dtype=np.float32)],
            outputs=[ct.TensorType(name="robustness", dtype=np.float32)],
            convert_to="mlprogram",
            compute_precision=ct.precision.FLOAT16,
            minimum_deployment_target=ct.target.iOS16,
        )
        out_path = OUT
    except Exception as e:
        print(f"mlprogram export unavailable ({type(e).__name__}: {e});"
              " falling back to neuralnetwork")
        mlmodel = ct.convert(
            traced,
            inputs=[ct.TensorType(name="features", shape=(1, IN_CH, h, w),
                                  dtype=np.float32)],
            convert_to="neuralnetwork",
        )
        out_path = os.path.splitext(OUT)[0] + ".mlmodel"
        # The neuralnetwork path cannot be given an output name up front, so
        # it lands on an autogenerated one (var_NN) that changes whenever the
        # graph does. Rename it, or the C++ side would key on a moving target.
        from coremltools.models.utils import rename_feature
        spec = mlmodel.get_spec()
        rename_feature(spec, spec.description.output[0].name, "robustness")
        mlmodel = ct.models.MLModel(spec)

    mlmodel.short_description = (
        "Per-pixel correction confidence C in [0,1] for the handheld "
        "multi-frame super-resolution robustness mask. The pipeline uses "
        "R_final = R_analytic * C, so this output can only lower the mask."
    )
    try:
        mlmodel.input_description["features"] = (
            f"{IN_CH} planes: ref mean/std RGB, warped comp mean RGB, flow "
            "dx/dy, flow span M, noise sigma, log1p(d^2/sigma^2), analytic R, "
            "flow residual and its span, ref high-frequency energy, match "
            "quality and isolation, and the spatial residual block (ref luma, "
            "warped comp luma, signed residual, ref gradient x/y, displacement "
            "estimate, residual/sigma)."
        )
        mlmodel.output_description["robustness"] = (
            "Correction confidence C in [0,1]; multiply the analytic mask by it."
        )
    except Exception:
        pass
    mlmodel.save(out_path)
    print("wrote", out_path)

    # The check that stops a silent fail-closed. Print what the SPEC says, not
    # what this script intended.
    spec = mlmodel.get_spec()
    inp = spec.description.input[0]
    print(f"spec input '{inp.name}' shape: "
          f"{list(inp.type.multiArrayType.shape)}  "
          f"(expect channel dim {IN_CH} == kRobustnessNnChannels)")
    print(f"spec output '{spec.description.output[0].name}'")

    # Parity check against the PyTorch model on random input -- catches a
    # conversion that silently reorders or drops a layer.
    try:
        probe = np.random.RandomState(0).randn(1, IN_CH, 96, 96).astype(np.float32)
        with torch.no_grad():
            ref_out = model(torch.from_numpy(probe)).numpy()
        got = mlmodel.predict({"features": probe})["robustness"]
        err = float(np.abs(ref_out - got).max())
        print(f"max |coreml - torch| = {err:.5f}  ({'OK' if err < 2e-2 else 'MISMATCH'})")
    except Exception as e:                      # no Core ML runtime off-Mac
        print("parity check skipped (needs a Mac runtime):", e)


if __name__ == "__main__":
    main()
