#pragma once
// GENERATED by tools/tile_reject_nn/export_weights.py -- do not edit.
// Tiny darken-only tile-reject NN: 7 features -> 8 -> 1 (sigmoid).
// Features (order): d_over_sigma, flow_grad_mag, dist_norm, pred_err, ref_grad_mag, flow_div, flow_curl
// Flat layout: mu[7], sd[7], W1[8*7], b1[8], W2[8], b2[1].
namespace hhsr {
inline constexpr int   kTileRejectFeat   = 7;
inline constexpr int   kTileRejectHidden = 8;
inline constexpr int   kTileRejectWeightCount = 87;
inline constexpr float kTileRejectW[87] = { 2.49141288e+00f, 4.16954184e+00f, 7.67397523e-01f, 1.07012105e+00f, 1.01738935e-02f, 7.77177334e-01f, 4.59929287e-01f, 6.34751987e+00f, 2.72394133e+00f, 2.87522137e-01f, 9.69069898e-01f, 2.11401787e-02f, 5.53291130e+00f, 2.47941256e+00f, -1.51824343e+00f, -1.00923610e+00f, -8.34636390e-02f, -1.09109735e+00f, -4.64175753e-02f, 6.31425306e-02f, 7.53141046e-01f, -2.42286295e-01f, 7.90066600e-01f, 5.65865934e-02f, 1.46764660e+00f, 1.70740187e-01f, 1.18598938e-01f, 1.39925241e-01f, -1.16835147e-01f, -7.61025995e-02f, 4.50226396e-01f, 1.66911280e+00f, -6.73600197e-01f, -9.93862599e-02f, -8.15979093e-02f, 7.33144432e-02f, 1.15431786e-01f, -1.29787058e-01f, 2.67216146e-01f, -2.72644567e+00f, 3.59627515e-01f, -1.49368912e-01f, -6.47528946e-01f, -6.42846048e-01f, -1.54506087e-01f, -8.52809846e-01f, 6.87423721e-02f, -6.02257699e-02f, -1.41839170e+00f, -6.32771134e-01f, -1.21551551e-01f, 6.83034658e-02f, -4.52934116e-01f, 1.11104056e-01f, -2.07026988e-01f, 2.29181841e-01f, -1.62842020e-01f, 6.66208804e-01f, 2.46711656e-01f, 2.16051388e+00f, 9.37111005e-02f, 2.12038398e-01f, 5.07896878e-02f, 1.36431947e-01f, -8.43657777e-02f, -7.20330654e-03f, 1.61329880e-02f, -7.66927242e+00f, 5.72927222e-02f, 4.85991361e-04f, 8.68712544e-01f, 2.82598019e+00f, -6.71931684e-01f, 1.56587768e+00f, 6.71826541e-01f, 1.53982508e+00f, 1.32753515e+00f, -2.68527079e+00f, 4.57372338e-01f, 1.00911963e+00f, 5.34130275e-01f, 5.02922952e-01f, 3.25737059e-01f, 4.90567595e-01f, -1.17631400e+00f, 1.47886467e+00f, -7.57088423e-01f };
// Offsets into kTileRejectW
inline constexpr int kTR_MU = 0;
inline constexpr int kTR_SD = 7;
inline constexpr int kTR_W1 = 14;
inline constexpr int kTR_B1 = 70;
inline constexpr int kTR_W2 = 78;
inline constexpr int kTR_B2 = 86;
} // namespace hhsr
