"""Export a trained sr_gate to core/sr_gate_weights.h.

    python export_weights.py --ckpt sr_gate.pt

One flat float array in a documented order, plus the shape constants. Flat and
not nested because the same numbers are uploaded verbatim to the GPU as a
device buffer: the Metal kernel indexes this exact layout, so there is one
definition of it rather than a C++ nesting and a separate GPU packing that can
drift.

    conv0 W  [width][in][3][3]      conv0 b [width]
    conv1 W  [width][width][3][3]   conv1 b [width]
    conv2 W  [width][width][3][3]   conv2 b [width]
    head  W  [1][width]             head  b [1]
"""
from __future__ import annotations

import argparse
import os
import sys

import io

import numpy as np
import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gate
import srsim

HEADER = '''// Generated by tools/sr_gate/export_weights.py -- do not edit by hand.
//
// sr_gate: the learned per-frame robustness mask (Config::sr_gate_enabled).
// See core/sr_gate.h for what the features are and tools/sr_gate/train.py for
// what it was trained against.
//
// %(nparam)d parameters, %(steps)s training steps.
// Trained on synthesised bursts from real Bayer DNG, against the merged image
// the pipeline would produce with perfect alignment and nothing rejected.
#pragma once

#include "types.h"

namespace hhsr {

// Layout, flat, because these same floats are uploaded to the GPU verbatim:
//   conv0 W [width][in][3][3], conv0 b [width],
//   conv1 W [width][width][3][3], conv1 b [width],
//   conv2 W [width][width][3][3], conv2 b [width],
//   head  W [1][width],           head  b [1]
static const int kSrGateWeightCount = %(nparam)d;

static const f32 kSrGateWeights[%(nparam)d] = {
%(weights)s};

}  // namespace hhsr
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--ckpt', default='sr_gate.pt')
    ap.add_argument('--out', default=None)
    a = ap.parse_args()
    here = os.path.dirname(os.path.abspath(__file__))
    ckpt_path = a.ckpt if os.path.isabs(a.ckpt) else os.path.join(here, a.ckpt)
    ck = torch.load(ckpt_path, map_location='cpu', weights_only=True)
    net = gate.SRGate(in_ch=ck['in_ch'], width=ck['width'],
                      dilations=ck['dilations'])
    net.load_state_dict(ck['state_dict'])

    flat = []
    for conv in net.convs:
        flat.append(conv.weight.detach().numpy().ravel())
        flat.append(conv.bias.detach().numpy().ravel())
    flat.append(net.head.weight.detach().numpy().ravel())
    flat.append(net.head.bias.detach().numpy().ravel())
    w = np.concatenate(flat).astype(np.float32)
    assert w.size == net.n_params(), (w.size, net.n_params())
    assert tuple(ck['dilations']) == gate.DILATIONS, \
        'core/sr_gate.h hardcodes the dilations; regenerate it too'
    # Checked against what the C++ will actually run -- core/sr_gate_shared.h --
    # and NOT against srsim.NUM_FEATURES. The simulator can build more channels
    # than the shipped net consumes (8-11 were measured neutral and are not
    # shipped), so comparing with it would refuse a perfectly good export.
    hdr = os.path.join(here, '..', '..', 'core', 'sr_gate_shared.h')
    want = None
    for line in io.open(hdr, encoding='utf-8'):
        if line.startswith('#define SRG_FEATURES'):
            want = int(line.split()[2])
    assert want is not None, 'SRG_FEATURES not found in ' + hdr
    assert ck['in_ch'] == want, (
        'checkpoint has %d input channels but core/sr_gate_shared.h declares '
        'SRG_FEATURES %d -- the app would feed the net the wrong feature plane'
        % (ck['in_ch'], want))

    lines = []
    for i in range(0, w.size, 6):
        lines.append('    ' + ' '.join('%.8ef,' % v for v in w[i:i + 6]))
    out = a.out or os.path.join(here, '..', '..', 'core', 'sr_gate_weights.h')
    out = os.path.abspath(out)
    with open(out, 'w', newline='\n') as f:
        f.write(HEADER % dict(nparam=w.size, steps=ck.get('steps', '?'),
                              weights='\n'.join(lines) + '\n'))
    print('wrote %s (%d params)' % (out, w.size))


if __name__ == '__main__':
    main()
