"""Export the artifact U-Net to core/sr_gate_unet_weights.h.

    python export_unet.py --ckpt sr_gate_art.pt

Same principle as export_weights.py: ONE flat float array in a documented order,
because the identical bytes are uploaded to the GPU as a device buffer and the
Metal kernels index this exact layout. A C++ nesting plus a separate GPU packing
would agree the day they were written and not a month later.

Layout, in order:

    e1 W [base][in][3][3]            e1 b [base]
    e2 W [base][base][3][3]          e2 b [base]
    d1 W [mid][base][3][3]           d1 b [mid]
    b1 W [mid][mid][3][3]            b1 b [mid]      dilation SRGU_DIL0
    b2 W [mid][mid][3][3]            b2 b [mid]      dilation SRGU_DIL1
    u1 W [base][mid + base][3][3]    u1 b [base]
    head W [1][base]                 head b [1]

The head is LINEAR -- it emits log1p(artifact in noise sigma), not a mask. The
mask is produced afterwards by the policy in sr_gate.cpp, which is where tau
lives.
"""
from __future__ import annotations

import argparse
import io
import os
import sys

import numpy as np
import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gate

HEADER = '''// Generated by tools/sr_gate/export_unet.py -- do not edit by hand.
//
// The artifact-predicting U-Net (Config::sr_gate_unet_enabled).
//
// It does not emit a mask. It emits log1p of the artifact that merging this
// frame would introduce at this pixel, in units of the local noise sigma, and
// sr_gate_unet_mask() turns that into R through a policy whose tolerance is
// Config::sr_gate_tau. Keeping those apart is deliberate: the network predicts
// what will happen, which is a fact about the burst, while tau decides how much
// of it is acceptable, which is a preference and is tunable without retraining.
//
// %(nparam)d parameters, %(steps)s training steps, trained with a pinball loss
// at q=%(q)s so under-predicting an artifact (merging a ghost) costs %(ratio).0fx
// over-predicting it (rejecting a good frame).
//
// Flat, in the order core/sr_gate_shared.h's SRGU_OFF_* name:
//   e1 W [base][in][3][3],        e1 b [base]
//   e2 W [base][base][3][3],      e2 b [base]
//   d1 W [mid][base][3][3],       d1 b [mid]
//   b1 W [mid][mid][3][3],        b1 b [mid]
//   b2 W [mid][mid][3][3],        b2 b [mid]
//   u1 W [base][mid+base][3][3],  u1 b [base]
//   head W [1][base],             head b [1]
#pragma once
#include "types.h"

namespace hhsr {

// %(nparam)d floats.
static const f32 kSrGateUNetWeights[] = {
'''

FOOTER = '''};

static_assert(sizeof(kSrGateUNetWeights) / sizeof(f32) == SRGU_WEIGHTS_N,
              "sr_gate_unet_weights.h and sr_gate_shared.h disagree on the "
              "parameter count -- re-run tools/sr_gate/export_unet.py");

}  // namespace hhsr
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--ckpt', default='sr_gate_art.pt')
    ap.add_argument('--out', default='../../core/sr_gate_unet_weights.h')
    a = ap.parse_args()

    here = os.path.dirname(os.path.abspath(__file__))
    ck = torch.load(a.ckpt if os.path.isabs(a.ckpt)
                    else os.path.join(here, a.ckpt),
                    map_location='cpu', weights_only=False)
    net = gate.unet_from_checkpoint(ck)
    if not net.linear_head:
        raise SystemExit('this exporter is for the artifact net (linear head)')

    base = net.e1.weight.shape[0]
    mid = net.d1.weight.shape[0]
    in_ch = net.e1.weight.shape[1]
    flat = []
    for conv in (net.e1, net.e2, net.d1, net.b1, net.b2, net.u1, net.head):
        flat.append(conv.weight.detach().numpy().ravel())
        flat.append(conv.bias.detach().numpy().ravel())
    w = np.concatenate(flat).astype(np.float32)
    assert w.size == net.n_params(), (w.size, net.n_params())

    q = float(ck.get('q', 0.9))
    txt = HEADER % {'nparam': w.size, 'steps': ck.get('steps', '?'),
                    'q': q, 'ratio': q / max(1 - q, 1e-6)}
    def lit(v):
        # '%g' alone yields "0" for zero, and "0f" is not a C++ literal -- the
        # compiler reports it as a missing operator""f, which reads like a
        # language-version problem rather than a formatting one. Anything with
        # no '.' and no exponent needs one before the suffix.
        t = '%.9g' % float(v)
        if '.' not in t and 'e' not in t and 'E' not in t:
            t += '.0'
        return t + 'f'

    for i in range(0, w.size, 8):
        txt += '    ' + ', '.join(lit(v) for v in w[i:i + 8]) + ',\n'
    txt += FOOTER

    outp = a.out if os.path.isabs(a.out) else os.path.join(here, a.out)
    io.open(outp, 'w', encoding='utf-8', newline='\n').write(txt)
    print('wrote %s' % os.path.normpath(outp))
    print('  in_ch %d  base %d  mid %d  dil %s  -> %d floats'
          % (in_ch, base, mid, net.dil, w.size))
    print('  tau %.2f  beta %.2f  q %.2f  vis %.1f sigma  (from the checkpoint)'
          % (ck.get('tau', 1.0), ck.get('beta', 0.5), q,
             ck.get('vis_sigma', 3.0)))
    print()
    print('shape constants for core/sr_gate_shared.h:')
    print('  #define SRGU_IN %d' % in_ch)
    print('  #define SRGU_BASE %d' % base)
    print('  #define SRGU_MID %d' % mid)
    print('  #define SRGU_DIL0 %d' % net.dil[0])
    print('  #define SRGU_DIL1 %d' % net.dil[1])
    print('  #define SRGU_WEIGHTS_N %d' % w.size)


if __name__ == '__main__':
    main()
