#!/usr/bin/env python3
"""Generate bundled Pixel 4a robustness noise curves from 460-main .npy data."""

from __future__ import annotations

from pathlib import Path

import numpy as np


ISOS = (50, 100, 200, 400, 800, 1600, 3200)


def format_array(name: str, values: np.ndarray) -> str:
    values = np.asarray(values, dtype=np.float32)
    lines = [f"static constexpr float {name}[kBins] = {{"]
    for i in range(0, values.size, 8):
        chunk = ", ".join(f"{float(v):.9g}f" for v in values[i : i + 8])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    repo = Path(__file__).resolve().parents[1]
    data = repo.parent / "460-main" / "460-main" / "data"
    out = repo / "core" / "pixel4a_noise_curves.h"

    chunks = [
        "#pragma once",
        "//",
        "// Generated by tools/generate_pixel4a_noise_curves.py from",
        "// ../460-main/460-main/data/noise_model_{std,diff}_ISO_*.npy.",
        "// These are the Pixel 4a Monte Carlo correction curves used by the",
        "// Python implementation's optional precomputed-curve path.",
        "//",
        "#include <cstddef>",
        "",
        "namespace hhsr {",
        "namespace pixel4a_noise {",
        "",
        "static constexpr int kBins = 1001;",
        "static constexpr int kIsoCount = 7;",
        "static constexpr int kIsos[kIsoCount] = {50, 100, 200, 400, 800, 1600, 3200};",
        "",
    ]

    for iso in ISOS:
        std_path = data / f"noise_model_std_ISO_{iso}.npy"
        diff_path = data / f"noise_model_diff_ISO_{iso}.npy"
        std = np.load(std_path)
        diff = np.load(diff_path)
        if std.shape != (1001,) or diff.shape != (1001,):
            raise ValueError(f"Unexpected curve shape for ISO {iso}: {std.shape}, {diff.shape}")
        chunks.append(format_array(f"kStdIso{iso}", std))
        chunks.append("")
        chunks.append(format_array(f"kDiffIso{iso}", diff))
        chunks.append("")

    chunks.extend(
        [
            "static constexpr const float* kStdCurves[kIsoCount] = {",
            "    kStdIso50, kStdIso100, kStdIso200, kStdIso400, kStdIso800, kStdIso1600, kStdIso3200,",
            "};",
            "",
            "static constexpr const float* kDiffCurves[kIsoCount] = {",
            "    kDiffIso50, kDiffIso100, kDiffIso200, kDiffIso400, kDiffIso800, kDiffIso1600, kDiffIso3200,",
            "};",
            "",
            "inline int index_for_iso(int iso) {",
            "    for (int i = 0; i < kIsoCount; ++i) {",
            "        if (kIsos[i] == iso) return i;",
            "    }",
            "    return -1;",
            "}",
            "",
            "} // namespace pixel4a_noise",
            "} // namespace hhsr",
            "",
        ]
    )

    out.write_text("\n".join(chunks), encoding="utf-8")


if __name__ == "__main__":
    main()
